{{ if .Values.runtime_overrides.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: weaviate-runtime-overrides
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  overrides.yaml: |-
{{ .Values.runtime_overrides.values | toYaml | nindent 2 }}

{{ end }}
